{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.kt2ts",
    "module": "kt2ts-ksp-generator",
    "version": "0.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kt2ts-ksp-generator-0.0.8.jar",
          "url": "kt2ts-ksp-generator-0.0.8.jar",
          "size": 74276,
          "sha512": "19e2e23df3d699d676d082a42f793eec2c305baf1c248f38918764644d285490b6f71efe286dd1950f1b67236e0f8225ad81b50590a63e78cbe4a383a28a3f35",
          "sha256": "cbdf95c4f23374ee1c82d70bf62291cc60573a09091152687d62c6c849f6b3f5",
          "sha1": "1ac913dcdbae401d9dc2201fef74485c3324baf5",
          "md5": "b5773708d5f2a4397c764dd0f4576d0a"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "io.github.kt2ts",
          "module": "kt2ts-annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.8.21-1.0.11"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20230227"
          }
        }
      ],
      "files": [
        {
          "name": "kt2ts-ksp-generator-0.0.8.jar",
          "url": "kt2ts-ksp-generator-0.0.8.jar",
          "size": 74276,
          "sha512": "19e2e23df3d699d676d082a42f793eec2c305baf1c248f38918764644d285490b6f71efe286dd1950f1b67236e0f8225ad81b50590a63e78cbe4a383a28a3f35",
          "sha256": "cbdf95c4f23374ee1c82d70bf62291cc60573a09091152687d62c6c849f6b3f5",
          "sha1": "1ac913dcdbae401d9dc2201fef74485c3324baf5",
          "md5": "b5773708d5f2a4397c764dd0f4576d0a"
        }
      ]
    }
  ]
}
