{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.kt2ts",
    "module": "kt2ts-ksp-generator",
    "version": "0.0.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kt2ts-ksp-generator-0.0.21.jar",
          "url": "kt2ts-ksp-generator-0.0.21.jar",
          "size": 104148,
          "sha512": "b7f30bf920abcb7457f83a30290eb184da514e93133676b6ab078475c2acb1f935b4a682df9b42958250b0bd6b4efdcb0e97e8966decbb27fc7c1de33519536e",
          "sha256": "9f12bbe5463c2899984ddd681f4d42d4ddd4d71b5b7e7a9d76f2fd56976f6817",
          "sha1": "5fa167becc6689c1d4a53a388e1c11c30c48d207",
          "md5": "95e1cad3c87b49b1d8c88cca97558ac8"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "io.github.kt2ts",
          "module": "kt2ts-annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.8.21-1.0.11"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20230227"
          }
        }
      ],
      "files": [
        {
          "name": "kt2ts-ksp-generator-0.0.21.jar",
          "url": "kt2ts-ksp-generator-0.0.21.jar",
          "size": 104148,
          "sha512": "b7f30bf920abcb7457f83a30290eb184da514e93133676b6ab078475c2acb1f935b4a682df9b42958250b0bd6b4efdcb0e97e8966decbb27fc7c1de33519536e",
          "sha256": "9f12bbe5463c2899984ddd681f4d42d4ddd4d71b5b7e7a9d76f2fd56976f6817",
          "sha1": "5fa167becc6689c1d4a53a388e1c11c30c48d207",
          "md5": "95e1cad3c87b49b1d8c88cca97558ac8"
        }
      ]
    }
  ]
}
