{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.kt2ts",
    "module": "kt2ts-ksp-generator",
    "version": "0.0.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kt2ts-ksp-generator-0.0.22.jar",
          "url": "kt2ts-ksp-generator-0.0.22.jar",
          "size": 105827,
          "sha512": "dcbc93dbbd6f8cbe0b21e018bf8bcd6d45f71473148a7f976de87d1cb2062c3b20945fc6ac547dbf7601dc5005f1e396c30b0cfc31c254fd930e21576ee525ac",
          "sha256": "46ad8784c22ed123f374b35cb43392e7152aa431a618d734b66e9d90be94837c",
          "sha1": "a11d7b4c363166455ed627220977f95816b81976",
          "md5": "966c89a05e6eb670f23f495071ec88b4"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "io.github.kt2ts",
          "module": "kt2ts-annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.8.21-1.0.11"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20230227"
          }
        }
      ],
      "files": [
        {
          "name": "kt2ts-ksp-generator-0.0.22.jar",
          "url": "kt2ts-ksp-generator-0.0.22.jar",
          "size": 105827,
          "sha512": "dcbc93dbbd6f8cbe0b21e018bf8bcd6d45f71473148a7f976de87d1cb2062c3b20945fc6ac547dbf7601dc5005f1e396c30b0cfc31c254fd930e21576ee525ac",
          "sha256": "46ad8784c22ed123f374b35cb43392e7152aa431a618d734b66e9d90be94837c",
          "sha1": "a11d7b4c363166455ed627220977f95816b81976",
          "md5": "966c89a05e6eb670f23f495071ec88b4"
        }
      ]
    }
  ]
}
