{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.kt2ts",
    "module": "kt2ts-ksp-generator",
    "version": "0.0.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kt2ts-ksp-generator-0.0.17.jar",
          "url": "kt2ts-ksp-generator-0.0.17.jar",
          "size": 82592,
          "sha512": "be5ed451edf0f1442fb83e8dd92a3bdc2444d971c9ec41fddc247874c1e64af7abb12915e9c756df93ad8df3a202316b45538f6264f15fc3344681fea52d239b",
          "sha256": "6b0a3fd5f550cff0c8ffd910ccd53302fc905895a84150b94da2d85a78a9b61a",
          "sha1": "f804d4dc05c96894db3eb62e22380ad311be8ec2",
          "md5": "f6381e087e0db687b2e384697dcb319e"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "io.github.kt2ts",
          "module": "kt2ts-annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.8.21-1.0.11"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20230227"
          }
        }
      ],
      "files": [
        {
          "name": "kt2ts-ksp-generator-0.0.17.jar",
          "url": "kt2ts-ksp-generator-0.0.17.jar",
          "size": 82592,
          "sha512": "be5ed451edf0f1442fb83e8dd92a3bdc2444d971c9ec41fddc247874c1e64af7abb12915e9c756df93ad8df3a202316b45538f6264f15fc3344681fea52d239b",
          "sha256": "6b0a3fd5f550cff0c8ffd910ccd53302fc905895a84150b94da2d85a78a9b61a",
          "sha1": "f804d4dc05c96894db3eb62e22380ad311be8ec2",
          "md5": "f6381e087e0db687b2e384697dcb319e"
        }
      ]
    }
  ]
}
