{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.kt2ts",
    "module": "kt2ts-ksp-generator",
    "version": "0.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kt2ts-ksp-generator-0.0.4.jar",
          "url": "kt2ts-ksp-generator-0.0.4.jar",
          "size": 75300,
          "sha512": "37796f48511c2a1bb05c8bf728e957085ab26ec295915db0ac911ffbb9f9da2b2066c130aa2eaaee5d700ff65266ec2c278f176d41d7ece1d1a2afb46f597877",
          "sha256": "3998d4988bd34a87b26c7eb35de803faaba71b72099c57625ab309781c2a64c6",
          "sha1": "bed2e255fdf8ea252a83c39b7b161b98f7704bd6",
          "md5": "46b326785faa5c31ce95fa8139823ce0"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "io.github.kt2ts",
          "module": "kt2ts-annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.8.21-1.0.11"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20230227"
          }
        }
      ],
      "files": [
        {
          "name": "kt2ts-ksp-generator-0.0.4.jar",
          "url": "kt2ts-ksp-generator-0.0.4.jar",
          "size": 75300,
          "sha512": "37796f48511c2a1bb05c8bf728e957085ab26ec295915db0ac911ffbb9f9da2b2066c130aa2eaaee5d700ff65266ec2c278f176d41d7ece1d1a2afb46f597877",
          "sha256": "3998d4988bd34a87b26c7eb35de803faaba71b72099c57625ab309781c2a64c6",
          "sha1": "bed2e255fdf8ea252a83c39b7b161b98f7704bd6",
          "md5": "46b326785faa5c31ce95fa8139823ce0"
        }
      ]
    }
  ]
}
