{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.kt2ts",
    "module": "kt2ts-ksp-generator",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kt2ts-ksp-generator-0.0.2.jar",
          "url": "kt2ts-ksp-generator-0.0.2.jar",
          "size": 73682,
          "sha512": "a06e1087748f6d22932a175c6b37782c162d55dfd05ec45f85153a06d17cf18e4bcb65e507dc9e60e38827494dec59e7b4c12bb31c87c7317f166c0cdd4566ff",
          "sha256": "0962abb97a135b72e7c4d30a5af55e8e3c1eed1580de388b2fe146fd8a0a8a31",
          "sha1": "b75466735c880124a7b43aa996a03a35d52c23fb",
          "md5": "b86ed989085b79e90a2210919fa808c2"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "io.github.kt2ts",
          "module": "kt2ts-annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.8.21-1.0.11"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20230227"
          }
        }
      ],
      "files": [
        {
          "name": "kt2ts-ksp-generator-0.0.2.jar",
          "url": "kt2ts-ksp-generator-0.0.2.jar",
          "size": 73682,
          "sha512": "a06e1087748f6d22932a175c6b37782c162d55dfd05ec45f85153a06d17cf18e4bcb65e507dc9e60e38827494dec59e7b4c12bb31c87c7317f166c0cdd4566ff",
          "sha256": "0962abb97a135b72e7c4d30a5af55e8e3c1eed1580de388b2fe146fd8a0a8a31",
          "sha1": "b75466735c880124a7b43aa996a03a35d52c23fb",
          "md5": "b86ed989085b79e90a2210919fa808c2"
        }
      ]
    }
  ]
}
