{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.kt2ts",
    "module": "kt2ts-ksp-generator",
    "version": "0.0.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kt2ts-ksp-generator-0.0.23.jar",
          "url": "kt2ts-ksp-generator-0.0.23.jar",
          "size": 107608,
          "sha512": "03cf44455ba688bd94ed71da13f581c415c9df09355da493f60407a17c879ab3e3baadba2b86276aff65d745ac38a994196dd00c370cab386f467399152aad8f",
          "sha256": "7030fdc0b45f5cb16c54fd8ab79c84453f8b600d1c5cc0fcd4e98d51e7361365",
          "sha1": "6dc4dcacf719f979f8780568cf8864ceb9b39ae0",
          "md5": "4064e2c8518a5c07d9bff470374b8a4f"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "io.github.kt2ts",
          "module": "kt2ts-annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.8.21-1.0.11"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20230227"
          }
        }
      ],
      "files": [
        {
          "name": "kt2ts-ksp-generator-0.0.23.jar",
          "url": "kt2ts-ksp-generator-0.0.23.jar",
          "size": 107608,
          "sha512": "03cf44455ba688bd94ed71da13f581c415c9df09355da493f60407a17c879ab3e3baadba2b86276aff65d745ac38a994196dd00c370cab386f467399152aad8f",
          "sha256": "7030fdc0b45f5cb16c54fd8ab79c84453f8b600d1c5cc0fcd4e98d51e7361365",
          "sha1": "6dc4dcacf719f979f8780568cf8864ceb9b39ae0",
          "md5": "4064e2c8518a5c07d9bff470374b8a4f"
        }
      ]
    }
  ]
}
