{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.kt2ts",
    "module": "kt2ts-ksp-generator",
    "version": "0.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kt2ts-ksp-generator-0.0.14.jar",
          "url": "kt2ts-ksp-generator-0.0.14.jar",
          "size": 77761,
          "sha512": "90fa1cd213d2d51b802c0ce5cd3e13470c26c58d2d12be5b9e6b69f453674f167de7a15149cc56dbb08f13720fca8fb23764a3e0aefc458948e95fc27b253429",
          "sha256": "d33c73a6a58138a61af73cd5428b003005efde1ad114272dfdbd8f7ff06c9481",
          "sha1": "ddaa952ebc620a507fdc57e2f2df1c8b74bdaa11",
          "md5": "96ecb3ef544d291e4ecc9aa7e0eedeb8"
        }
      ]
    },
    {
      "name": "runtimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        },
        {
          "group": "io.github.kt2ts",
          "module": "kt2ts-annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.8.21-1.0.11"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20230227"
          }
        }
      ],
      "files": [
        {
          "name": "kt2ts-ksp-generator-0.0.14.jar",
          "url": "kt2ts-ksp-generator-0.0.14.jar",
          "size": 77761,
          "sha512": "90fa1cd213d2d51b802c0ce5cd3e13470c26c58d2d12be5b9e6b69f453674f167de7a15149cc56dbb08f13720fca8fb23764a3e0aefc458948e95fc27b253429",
          "sha256": "d33c73a6a58138a61af73cd5428b003005efde1ad114272dfdbd8f7ff06c9481",
          "sha1": "ddaa952ebc620a507fdc57e2f2df1c8b74bdaa11",
          "md5": "96ecb3ef544d291e4ecc9aa7e0eedeb8"
        }
      ]
    }
  ]
}
